//
//  NPConstants.h
//  Newton
//
//  Created by omer iqbal on 12/2/13.
//  Copyright (c) 2013 nus.cs3217. All rights reserved.
//

#import <Foundation/Foundation.h>
@interface NPConstants : NSObject
FOUNDATION_EXPORT const CGFloat WORLD_STEP;
FOUNDATION_EXPORT const CGFloat DEFAULT_MASS;
FOUNDATION_EXPORT const CGFloat GRAVITY;
FOUNDATION_EXPORT const CGFloat DEFAULT_RESTITUITION;
FOUNDATION_EXPORT const CGFloat DEFAULT_FRICTION;
FOUNDATION_EXPORT const CGFloat BIAS_CONST_1;
FOUNDATION_EXPORT const CGFloat BIAS_CONST_2;
FOUNDATION_EXPORT const int IMPULSE_ITERATIONS;
FOUNDATION_EXPORT const CGFloat ROTATION_EPSILON1;
FOUNDATION_EXPORT const CGFloat ROTATION_EPSILON2;
FOUNDATION_EXPORT const CGFloat BIAS_ROW;
FOUNDATION_EXPORT const CGFloat ACC_FACTOR;
FOUNDATION_EXPORT const CGFloat VELOCITY_EPSILON;
@end
